### ISSUE TITLE
Server attempts to load client class I18N

### ISSUE THREAD

**Issue by AviatorFuchs** [FairySteve/Mind#4]
**What's the problem?**
Server attempts to load client sided class I18N, when trying to execute a piece of command from the console.

**How to reproduce?**
1. Text a piece of command into the console pane. The command might could only be from those banned by the helper mod "Mind".
2. Press enter.
3. Crashes, featuring a NoClassDefFoundError: net/minecraft/client/resources/I18n.

**Server info?**
The server was downloaded from the project's release page, and the version is 0.1.2. I ran the server pack directly on my laptop. 

**Log?**
https://paste.ubuntu.com/p/jRtDR2gyvW/
This is the log when I tried to excute "/tp" via the console pane.

**Comment by FairySteve** [comment]
fixed

**Comment by lyuxc-unknow** [comment]
It has been fixed because we accidentally used a syntax that the server does not have (but you still can't use some commands)
