### ISSUE TITLE
下载不了EnderTweaker-1.12.2-1.2.2-patched.jar

### ISSUE THREAD

**Issue by Water-Moon** [FairySteve/Mind#7]
ModDirector配置中的 EnderTweaker-1.12.2-1.2.2-patched.jar 这个文件指向了这个Git仓库上面一个不存在或者已经被移除的地址，导致无法启动，什么鬼……

它本来应该和其他几个mod一起位于[这里](https://github.com/FairySteve/Mind/releases/tag/0.2.1-patchedMods)，但似乎只有EnderTweaker被删除了。。。

**Comment by Water-Moon** [comment]
对了还有，建议更新下整合包里的 RandomTweaker-1.2.1.jar 这个模组，这东西也有服务端加载不了的问题（参见[这个](https://github.com/ikexing-cn/RandomTweaker/issues/51)）……

**Comment by Water-Moon** [comment]
然后就是如果您把RandomTweaker更新到1.2.5的话，有一个要注意的地方就是[这个](https://github.com/ikexing-cn/RandomTweaker/blob/4015ca5e60c2bf1111da9d614387a3b6f3b1a092/src/main/java/ink/ikx/rt/api/mods/jei/IJeiUtilsWithBotania.java#L17)方法的名称变了，所以您这个整合的脚本里面[这里](https://github.com/FairySteve/Mind/blob/1040600c6a6d411df3f542944ba45386c83b13af/.minecraft/scripts/Mods/CustomJEIPanel.zs#L26)和[这里](https://github.com/FairySteve/Mind/blob/1040600c6a6d411df3f542944ba45386c83b13af/.minecraft/scripts/Mods/CustomJEIPanel.zs#L34)的方法`createJEIManaBarElement`要改成`createJeiManaBarElement`这样子
qwq

**Comment by Water-Moon** [comment]
还有个小建议，希望您可以推出最新版整合包对应的服务器端，并且在服务器端去掉您在Mind-0.2这个模组里面进行的一些关于`CommandEvent`的检查，否则这对于一个服主来说是非常难堪的……

**Comment by lyuxc-unknow** [comment]
Mind模组的最新开发工作区丢失（重装系统未备份），关于RT部分问题已经修复,EnderTweaker作者以合并PR且在CF更新了模组版本，故删除了GitHub上的修复文件（相关下载文件也一删除）
